DAO models definition
ncedu-tlt/2020-ux-booking pull request #42
Opened 2021-04-08 18:48 UTC by Mirzoeva-Marjona

2021-04-08 19:28 UTC, ocassio requested changes
Что еще стоит сделать:
1. Почитай про каскады. Особенно нам сейчас интересно каскадное удаление, когда мы к примеру удаляем отели, а при этом автоматом удаляются комнаты, отзывы и т.п.
2. Проверь, что у нас является опциональным, а что нет. Надо бы отразить этот факт как в TS, так и в декораторах.
3. (Опционально) Если сразу есть понимание, что какое-то поле с данными из связанной таблицы будут использоваться крайне редко, то есть смысл сделать его ленивым, чтобы данные запрашивались только по явному требованию.

2021-04-08 19:28 UTC, ocassio commented on apps/backend/src/app/modules/db/domain/addresses.ts
> +export class Addresses {
Сущности обычно называют в единственном числе, так как это олицетворение одной записи.

2021-04-08 19:28 UTC, ocassio commented on apps/backend/src/app/modules/db/domain/addresses.ts
> +  streets: string;
Улицы?

2021-04-08 19:28 UTC, ocassio commented on apps/backend/src/app/modules/db/domain/board_basis.ts
> +@Entity('board_basis')
А вот таблички обычно в множественном числе идут)

2021-04-08 19:28 UTC, ocassio commented on apps/backend/src/app/modules/db/domain/booking.ts
> +  date_on: string;
JS поля в camelCase

2021-04-08 19:28 UTC, ocassio commented on apps/backend/src/app/modules/db/domain/booking_details.ts
> +  bookingDetailsBooking: BookingDetailsBooking[];
А зачем у нас тут многие-ко-многим? У нас же простая иерархия - весь заказ и информация по каждой комнате. Резервирование комнаты не может между несколькими заказами переиспользоваться.

2021-04-08 19:28 UTC, ocassio commented on apps/backend/src/app/modules/db/domain/bookmarks.ts
> +  id: string;
На самом деле тут id не нужен. Ты же можешь обычную связь многие-ко-многим использовать и не описывать отдельную сущность.

2021-04-08 19:28 UTC, ocassio commented on apps/backend/src/app/modules/db/domain/categories.ts
> +export class Categories {
Возможно стоит уточнить, что это именно категория сервисов.

2021-04-08 19:28 UTC, ocassio commented on apps/backend/tsconfig.json
> +  }
А это зачем? Это даже не для Angular конфигурация.

2021-04-18 08:36 UTC, ocassio requested changes

2021-04-18 08:36 UTC, ocassio commented on apps/backend/src/app/modules/db/domain/booking.dao.ts
> +  bookingDetail: BookingDetail;
Тут one-to-many должен быть. Мы же несколько номеров в рамках одного заказа резервируем.

2021-04-18 08:36 UTC, ocassio commented on apps/backend/src/app/modules/db/domain/booking.dao.ts
> +  bookingConditions: BookingCondition[];
А напомни, для чего это у нас?

2021-04-18 08:36 UTC, ocassio commented on apps/backend/src/app/modules/db/domain/service.dao.ts
> +  // category: Categories;
А почему категории удалены?

2021-04-18 08:36 UTC, ocassio commented on apps/backend/tsconfig.app.json
> +    "target": "es2017"
Это для чего?

2021-04-18 08:50 UTC, Mirzoeva-Marjona commented on apps/backend/src/app/modules/db/domain/booking.dao.ts
> +  bookingConditions: BookingCondition[];
Условия бронирования (бесплатная отмена, расчет картой, и тд.)

2021-04-18 08:51 UTC, Mirzoeva-Marjona commented on apps/backend/src/app/modules/db/domain/service.dao.ts
> +  // category: Categories;
Я пока не знаю, что с ними делать, жду когда появится связь с UI

2021-04-18 08:51 UTC, ocassio commented on apps/backend/src/app/modules/db/domain/booking.dao.ts
> +  bookingConditions: BookingCondition[];
Мы эти вещи привязывали к отелям, чтобы по ним потом фильтровать. С конкретным заказом оно вообще никак не должно связываться.

2021-04-18 08:55 UTC, Mirzoeva-Marjona commented on apps/backend/tsconfig.app.json
> +    "target": "es2017"
У меня была такая ошибка https://github.com/nrwl/nx/issues/2975, и я где-то нашла, что ее можно так исправить

2021-04-18 08:58 UTC, ocassio commented on apps/backend/tsconfig.app.json
> +    "target": "es2017"
Принял.

2021-04-18 14:27 UTC, Mirzoeva-Marjona commented on apps/backend/src/app/modules/db/domain/booking.dao.ts
> +  bookingDetail: BookingDetail;
Поправила

2021-04-18 14:27 UTC, Mirzoeva-Marjona commented on apps/backend/src/app/modules/db/domain/booking.dao.ts
> +  bookingConditions: BookingCondition[];
Поправила

2021-04-18 14:37 UTC, ocassio approved these changes

2021-04-18 14:37 UTC, merged