Feature/46 user registration
ncedu-tlt/2020-ux-booking pull request #48
Opened 2021-04-19 20:50 UTC by Mirzoeva-Marjona

2021-04-20 11:19 UTC, ocassio requested changes

2021-04-20 11:19 UTC, ocassio commented on apps/backend/src/app/modules/app/users/user.controller.ts
> +      res.status(HttpStatus.UNPROCESSABLE_ENTITY);
Такие проверки можно автоматизировать:
https://docs.nestjs.com/techniques/validation

2021-04-20 11:19 UTC, ocassio commented on apps/backend/src/app/modules/app/users/user.controller.ts
> +          return 'created';
created тут слать не надо, код уже обо всем говорит.

2021-04-20 11:19 UTC, ocassio commented on apps/backend/src/app/modules/app/users/user.controller.ts
> +          console.log('error');
Информативненько :)

2021-04-20 11:19 UTC, ocassio commented on apps/backend/src/app/modules/app/users/user.controller.ts
> +    const res = await entityManager
Используй репозиторий вместо entityManager. Намного удобнее.

2021-04-22 20:10 UTC, Mirzoeva-Marjona commented on apps/backend/src/app/modules/app/users/user.controller.ts
> +      res.status(HttpStatus.UNPROCESSABLE_ENTITY);
Поправила

2021-04-22 20:10 UTC, Mirzoeva-Marjona commented on apps/backend/src/app/modules/app/users/user.controller.ts
> +          return 'created';
Поправила

2021-04-22 20:11 UTC, Mirzoeva-Marjona commented on apps/backend/src/app/modules/app/users/user.controller.ts
> +    const res = await entityManager
Сделала

2021-04-23 08:43 UTC, ocassio requested changes

2021-04-23 08:43 UTC, ocassio commented on apps/backend/src/app/modules/app/users/user.service.ts
> +export class UserService {}
А что за пустой сервис?

2021-04-23 08:43 UTC, ocassio commented on apps/backend/src/app/modules/app/users/user.controller.ts
> +    const userRepository = getRepository(User);
Репозиторий лучше инжектить через конструктор.

2021-04-23 08:43 UTC, ocassio commented on apps/backend/src/app/modules/app/users/user.controller.ts
> +  async isValidEmail(email, userRepository): Promise<boolean> {
Этот метод должен быть приватным.

2021-04-23 08:43 UTC, ocassio commented on apps/backend/src/app/modules/app/users/user.controller.ts
> +    return (await userRepository.count({ email: email })) == 0;
Тут лучше разнести на две строки: получение и сравнение, чтобы легче было отлаживать.

2021-04-23 08:43 UTC, ocassio commented on apps/backend/src/app/modules/app/users/user.controller.ts
> +      return res.send('Such user is already registered');
Здесь обычно используются не полноценные фразы, а условленные коды, чтобы по ним фронт уже смог нарисовать красивое сообщение, а как именно оно будет выглядеть, решает он.

2021-05-13 18:26 UTC, Mirzoeva-Marjona commented
@ocassio Поправила

2021-05-14 13:43 UTC, ocassio commented on apps/backend/src/app/modules/app/users/user.controller.ts
> +      return res.send('Such user is already registered');
Я имел в виду замену текстовки, можно например подобным объектом:
```json
{
  "code": "alredy_exists",
  "message": "Such user is already registered"
}
```

Чтобы фронт за код зацепился и понял, что вот тут надо показать сообщение о том, что такой пользователь уже есть. Для такой ошибки 409 статус больше подходит, кстати.

2021-05-19 18:48 UTC, ocassio approved these changes

2021-05-19 18:48 UTC, merged