Feature/49 authentication
ncedu-tlt/2020-ux-booking pull request #53
Opened 2021-04-25 20:09 UTC by Mirzoeva-Marjona

2021-04-28 06:17 UTC, ocassio requested changes

2021-04-28 06:17 UTC, ocassio commented on apps/backend/src/app/modules/app/auth/auth.service.ts
> +  async validateUser(email: string, pass: string): Promise<any> {
any используем только в самых крайних случаях.

2021-04-28 06:17 UTC, ocassio commented on apps/backend/src/app/modules/app/auth/auth.service.ts
> +      access_token: this.jwtService.sign(payload)
camelCase

2021-04-28 06:17 UTC, ocassio commented on apps/backend/src/app/modules/app/auth/constants.ts
> +  secret: 'test'
Поместить в конфигурацию с переменными окружения.

2021-04-28 06:17 UTC, ocassio commented on apps/backend/src/app/modules/app/auth/jwt.strategy.ts
> +  async validate(payload: any) {
Снова any.

2021-04-28 06:17 UTC, ocassio commented on apps/backend/src/app/modules/app/users/users.service.ts
> +    return getRepository(User).findOne(
Репозитории инжектим через конструктор.

2021-04-28 06:17 UTC, ocassio commented on apps/backend/src/app/modules/app/auth/role.enum.ts
> +export enum DefRole {
1. Модели помещаем в соответствующую дерикторию.
2. Просто Role?
3. Значения enum пишем в UPPER_CASE.
4. Желательно делать их строковыми, так проще отлаживать: `USER = "user"`.

2021-04-28 06:17 UTC, ocassio commented on apps/backend/src/app/modules/app/app.controller.ts
> +  }
Эти эндпоинты хороши для проверки, но в финальном варианте их быть не должно. Надо их либо удалить, либо закомментировать и пометить как пример.

2021-04-28 06:17 UTC, ocassio commented on apps/backend/src/app/modules/app/app.controller.ts
> +  @Get('profile')
Тут советую сначала определять, что за API, а потом параметры доступа. Глазу проще.  
Ну и неплохо бы пути с `/` начинать.

2021-04-28 06:17 UTC, ocassio commented on apps/backend/src/app/modules/app/auth/local.strategy.ts
> +  async validate(username: string, password: string): Promise<any> {
И снова any

2021-04-28 06:17 UTC, ocassio commented on apps/backend/src/app/modules/app/auth/roles.guard.ts
> +    const defRolArr = [DefRole.user];
Давай использовать полные имена. А то я даже не сразу понял, что это такое :)

2021-04-28 06:17 UTC, ocassio commented on apps/backend/src/app/modules/app/auth/roles.guard.ts
> +    return requiredRoles.some(role => defRolArr?.includes(role));
Сомневаешься, что `defRolArr` будет иметь значение? Ты же его сама выше задала.

2021-04-28 06:17 UTC, ocassio commented on apps/backend/src/app/modules/app/users/user.controller.ts
> +    const roles = [await getRepository(Role).findOne({ name: 'admin' })];
Мы всех пользователей админами создаем?

2021-05-04 17:25 UTC, ocassio requested changes

2021-05-04 17:25 UTC, ocassio commented on apps/backend/src/app/modules/app/auth/constants.ts
>  };
Нет, смотри. Суть в том, чтобы иметь возможность конфигурации секрета от сервера к серверу без модификации исходного кода. Для этого у нас используется модуль конфигурации, как, к примеру, для порта или URL базы данных. Файлы окружений же используются для создания констант специфичных для различных вариантов сборок.

2021-05-08 17:12 UTC, ocassio commented on apps/backend/src/app/modules/app/auth/constants.ts
> +  secret: appConfig().jwtSecret
jwtConstants нужно убрать совсем. Вместо этого используй `JwtModule.registerAsync` для регистрации модуля и инжекти ConfigService.

2021-05-09 19:51 UTC, Mirzoeva-Marjona commented on apps/backend/src/app/modules/app/auth/constants.ts
> +  secret: appConfig().jwtSecret
Поправила

2021-05-11 11:27 UTC, ocassio approved these changes

2021-05-11 11:27 UTC, merged