Feature/28 table component
ncedu-tlt/2020-ux-booking pull request #64
Opened 2021-05-30 02:16 UTC by sidkate

table component

2021-05-30 17:52 UTC, NataliaKly requested changes

2021-05-30 17:52 UTC, NataliaKly commented on apps/frontend/src/app/common/table/table.component.html
> +        </div>
выравнивание немного подправить у строки с кнопкой, пробел лишний после class="td-icon". 
А почему тут именно этот класс? Это же часть таблицы, имеет смысл сделать это элементом блока table

2021-05-30 17:52 UTC, NataliaKly commented on apps/frontend/src/app/common/table/table.component.less
> +  &__body-row td span {
давай использовать селекторы классов, а не тегов, будем придерживаться методологии бэм

2021-05-30 17:52 UTC, NataliaKly commented on apps/frontend/src/app/common/table/table.component.less
> +  &__body-row .td-icon b-button-icon{
смысл бэм - свести к минимуму использование селекторов наследования и задать такой класс, по которому однозначно можно выбрать нужный элемент (или группу элементов). 
td-icon надо переименовать, т.к. это явно часть таблицы, а не отдельный блок
для b-button-icon тоже можно задать класс

2021-05-30 17:52 UTC, NataliaKly commented on apps/frontend/src/app/common/table/table.component.less
> +    border-bottom: 1px solid @color-grey-light;
1рх сверху + 1рх снизу = 2рх обводки между строками :) по мокапам 1рх

2021-05-30 17:52 UTC, NataliaKly commented on apps/frontend/src/app/common/table/table.component.less
> +    float: right;
не надо float, пожалуйста :) на hover же flex задан) нужно добавить свойство justify-content

2021-05-30 17:52 UTC, NataliaKly commented on apps/frontend/src/app/common/table/table.component.less
> +    box-shadow: 1px 1px 6px rgba(0, 50, 79, 0.3);
тень можно в mixins.less вынести, там уже есть одна тень, также сделать эту. Чтоб можно было переиспользовать для других компонент

2021-05-30 17:52 UTC, NataliaKly commented on apps/frontend/src/app/common/table/table.component.ts
> +  items: any[] = [];
any не используем, в других местах тоже поправить надо

2021-05-30 17:52 UTC, NataliaKly commented on apps/frontend/src/app/common/table/table.component.ts
> +export class TableButton {
здесь описано только одно поле, может этот класс лишний ?)

2021-05-30 17:52 UTC, NataliaKly commented on apps/frontend/src/app/common/table/table.component.ts
> +  @Input()
четыре инпут поля получилось. Давай в одну модель их объединим, table.model.ts к примеру

2021-06-06 13:26 UTC, sidkate commented on apps/frontend/src/app/common/table/table.component.ts
> +  @Input()
Модель - это не для объектов предметной области?

2021-06-07 07:33 UTC, NataliaKly commented on apps/frontend/src/app/common/table/table.component.ts
> +  @Input()
Ну и это тоже, да)
Конкретно здесь смысл такой: для работы компонента требуется определенный набор данных. Например, для компонента нотификаций это тип и текст, они друг от друга не зависят, любой текст отрисуется независимо от переданного типа. Причем тип можно не указывать вообще, тогда отрисуется тот, что задан по умолчанию. Т.е. для компонента нотификаций можно держать два инпут поля.
Для компонента таблички немного по-другому. У нас есть колонки, заголовки и строки, они связаны, и они все обязательные, если мы передадим разные данные (в колонках одно напишем, а в заголовках другое) или не передадим что-то из этого, то компонент работать не будет как мы ожидаем.
Что бы уменьшить вероятность сделать где-то ошибку, можно объединить эти поля в одно, и описать его структуру (как тип, интерфейс или класс).  И тогда при описании данных для таблички мы обязаны будем следовать этой описанной структуре и среда разработки еще на этапе написания кода подсветит нам ошибку, если мы что-то забыли вставить.

2021-06-21 07:15 UTC, NataliaKly approved these changes

2021-06-21 07:15 UTC, merged